### ISSUE TITLE
我有 build macOS 的執行檔

### ISSUE THREAD

**Issue by mosluce** [GpointChen/FFXIVChnTextPatch-GP#191]
要怎麼提供比較方便呢？

**Comment by mosluce** [comment]
release 
https://github.com/mosluce/FFXIVChnTextPatch-GP/releases/tag/latest

**Comment by onlineid** [comment]
請問M1的Macbook可以適用嗎？

**Comment by mosluce** [comment]
可以試試看，我目前還沒有 M1 的 mac QQ

Lyrebird ***@***.***> 於 2022年7月15日 週五 下午6:18寫道：

**Comment by Fredpkc** [comment]
Hi 我可以成功開啟Patch黨, 但請問mac FFXIV的預設路徑在哪？我選擇library/application support/Final Fantasy XIV ONLINE會顯示路徑錯誤

**Comment by Fredpkc** [comment]
![截圖 2022-07-28 下午10 48 03](https://user-images.githubusercontent.com/110171041/181566043-a1f7eb31-af69-4b44-b7f6-5d8acc719a8f.png)
![截圖 2022-07-28 下午10 48 22](https://user-images.githubusercontent.com/110171041/181566166-635fe99b-a4f0-4713-839d-2614656a0734.png)

**Comment by mosluce** [comment]
繼續點進去，路進應該是這樣
~/Library/Application\ Support/FINAL\ FANTASY\ XIV\
ONLINE/Bottles/published_Final_Fantasy/drive_c/Program\ Files\
\(x86\)/SquareEnix/FINAL\ FANTASY\ XIV\ -\ A\ Realm\ Reborn

Fredpkc ***@***.***> 於 2022年7月28日 週四 晚上10:48寫道：

**Comment by Fredpkc** [comment]
感謝...但在實際漢化的時候有Error:
Exception in thread "Thread-1" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at name.yumao.ffxiv.chn.builder.TexBlockBuilder.buildBlock(TexBlockBuilder.java:38)
	at name.yumao.ffxiv.chn.replace.ReplaceFont.replace(ReplaceFont.java:70)
	at name.yumao.ffxiv.chn.thread.ReplaceThread.run(ReplaceThread.java:46)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Fredpkc** [comment]
![截圖 2022-07-28 下午11 43 05](https://user-images.githubusercontent.com/110171041/181580787-1841c248-a64c-477c-8ff3-dc06757a5c2a.png)

**Comment by Fredpkc** [comment]
Java版本: 
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

我的MBP是M1, 但我想應該沒有影響

**Comment by mosluce** [comment]
@Fredpkc 
我的工具要搭配原作者那一包使用喔，我這包沒有語系檔

**Comment by Fredpkc** [comment]
@mosluce 我是按照你提供的步驟：
到 https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases 下載 FFXIVChnTextPatch_0706.rar 並解壓縮
下載 FFXIVChnTextPatch_0706_macos_intel.zip 解壓縮後會得到兩個資料夾和一個執行檔，搬到上面解壓縮同一資料夾中
雙擊 FFXIVChnTextPatchGP (沒有 .exe) 執行

這樣也沒有語系檔媽？

**Comment by mosluce** [comment]
FFXIVChnTextPatchGP 和 FFXIVChnTextPatchGP.exe 要在同一層喔

Fredpkc ***@***.***>於 2022年8月1日 週一，下午5:18寫道：

**Comment by Fredpkc** [comment]
了解 謝謝你了

**Comment by stussykaki** [comment]
> 了解 謝謝你了

你好，小弟剛進坑的新手，爬文找到這裡，也是跟你一樣卡了在font6.tex那裡，請問大大現在有解決了嗎？

**Comment by onlineid** [comment]
@mosluce 
成功中文化了，整個3.0都沒有遇到問題，特來致謝。辛苦了。

順便問一下，現在中文化質量最高的是用哪個方式呢？我現在用的是CSV的方式。但是遊戲語音還是英文，所以感覺有些翻譯還是不太準確。我知道這邊只是提供中文化的程式而不負責翻譯質量，只是希望可以借鑑前輩的經驗。

**Comment by Fredpkc** [comment]
> > 了解 謝謝你了
> 
> 你好，小弟剛進坑的新手，爬文找到這裡，也是跟你一樣卡了在font6.tex那裡，請問大大現在有解決了嗎？
 
沒有耶 我直接放棄  看英文了

**Comment by Fredpkc** [comment]
> @mosluce 成功中文化了，整個3.0都沒有遇到問題，特來致謝。辛苦了。
> 
> 順便問一下，現在中文化質量最高的是用哪個方式呢？我現在用的是CSV的方式。但是遊戲語音還是英文，所以感覺有些翻譯還是不太準確。我知道這邊只是提供中文化的程式而不負責翻譯質量，只是希望可以借鑑前輩的經驗。

大部分中文化是對岸的文本轉繁體過來的，質量已經很高了
我先前也是看英文玩，官方英文文本的順序跟一些對話官方中日文差很多不是直接翻譯，估計文本是有重寫的
所有你才會覺得中文字幕跟英文語音對不上吧

**Comment by onlineid** [comment]
> > @mosluce 成功中文化了，整個3.0都沒有遇到問題，特來致謝。辛苦了。
> > 順便問一下，現在中文化質量最高的是用哪個方式呢？我現在用的是CSV的方式。但是遊戲語音還是英文，所以感覺有些翻譯還是不太準確。我知道這邊只是提供中文化的程式而不負責翻譯質量，只是希望可以借鑑前輩的經驗。
> 
> 大部分中文化是對岸的文本轉繁體過來的，質量已經很高了 我先前也是看英文玩，官方英文文本的順序跟一些對話與官方中日文差很多，並不是直接翻譯。估計文本是有重寫。 所有你才會覺得中文字幕跟英文語音對不上吧

原來如此，明白了。感謝。
