### ISSUE TITLE
檔案打不進去

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#375]
GimmickTalk.EXH
 [INFO   ] Read :    EXD/GimmickTalk.EXH
 [WARNING] CSV Exception: For input string: "0
int32"
java.lang.NumberFormatException: For input string: "0
int32"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.valueOf(Unknown Source)
	at name.yumao.ffxiv.chn.replace.ReplaceEXDF.replace(ReplaceEXDF.java:192)
	at name.yumao.ffxiv.chn.thread.ReplaceThread.run(ReplaceThread.java:50)
	at java.base/java.lang.Thread.run(Unknown Source)
奇怪 不知道為什麼打不進去..?

**Comment by GpointChen** [comment]
看起來是檔案換行符（line ending）出了點問題，全部變成了unix的換行符，導致分析CSV的時候將兩行內容錯讀在一起。

預計下次更新時會修正。若現在有需要，你可以解壓後用這個檔案替代`resource\rawexd`內的同名檔案，然後還原、重新漢化。

[GimmickTalk.zip](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/12357340/GimmickTalk.zip)

**Comment by Liteya** [comment]
謝謝
