### ISSUE TITLE
漢化錯誤 EXD/Stain.EXH

### ISSUE THREAD

**Issue by Nokcc** [GpointChen/FFXIVChnTextPatch-GP#376]
[ReplaceEXDF] Now File : EXD/Stain.EXH
java.lang.NullPointerException
        at name.yumao.ffxiv.chn.replace.ReplaceEXDF.replace(ReplaceEXDF.java:307)
        at name.yumao.ffxiv.chn.thread.ReplaceThread.run(ReplaceThread.java:49)
        at java.base/java.lang.Thread.run(Thread.java:829)
請問係有咩問題？
之前成功漢化 但過左幾個月再重新試就有上面問題出現

**Comment by GpointChen** [comment]
你是用最新的漢化嗎？

**Comment by GpointChen** [comment]
過久沒有回覆，關閉此串。仍有問題可再回覆。
